name: list_detail_demo
description: Simple List and Detail View Demo
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  retrofit: ^4.0.1
  connectivity_plus: ^3.0.3
  realm: ^1.0.2
  realm_dart: ^1.0.2
  intl: ^0.18.0
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoe.ttf
        - asset: assets/fonts/Segoe-Italic.ttf
          style: italic
        - asset: assets/fonts/Segoe-Bold.ttf
          weight: 800
        - asset: assets/fonts/Segoe-Bold-Italic.ttf
          weight: 600
